# Generated by Django 5.0.7 on 2024-07-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('ConfirmPassword', models.CharField(max_length=50)),
                ('DOB', models.DateField(max_length=50)),
                ('Gender', models.CharField(max_length=1)),
            ],
        ),
    ]
