# Generated by Django 5.0.7 on 2024-07-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Gender',
            field=models.CharField(max_length=100),
        ),
    ]
